### PR TITLE
Ramp scene

### PR DESCRIPTION
**Pull request by dominikglandorf**
Adds a new scene, consisting of a ramp on a table and two movable objects

generate.jl draws ten random traces and visualized resulting trajectories from the two objects

Screenshot 2023-09-19 at 14 51 36

### CODE REVIEW

**Comment by dominikglandorf** [comment]
MCMC inference

Screenshot 2023-09-19 at 15 02 38

**Comment by dominikglandorf** [comment]
Particle Filter Inference
Screenshot 2023-09-19 at 15 36 03

**Comment by belledon** [comment]
thanks @dominikglandorf , it's hard to tell if inference is working properly. I think it might be. Can you try only inferring the mass of the ramp object?

**Comment by dominikglandorf** [comment]
@belledon Does this imply that the mass of the table object is assumed to be known? I think the MCMC proposal does not get accepted very often and it is hence inefficient. In the particle filter, I may plot the difference of masses to see how well it infers.

**Comment by belledon** [comment]
yes, for now, let's assume the mass of one of the objects; otherwise, the posterior will be multi-modal as there are several mass values that would yield the same mass ratio as the ground truth.  This will help visual posterior convergence as there should only be one mode in this case.

**Comment by iyildirim** [comment]
Alternatively you can model and infer relative mass -- the ratio of the two mass values
________________________________

**Comment by dominikglandorf** [comment]
Thank you. I think the narrow distribution of ratios and high log scores can confirm the successful inference:
Screenshot 2023-09-19 at 20 44 53

**Comment by belledon** [comment]
what is the ground truth value for this trial?

**Comment by dominikglandorf** [comment]
the top left plot is the ground truth (masses in the title), the middle top is the last particle after inference. i will clarify plot titles!

**Comment by belledon** [comment]
ah i see, so we would should see a ~4:1 ratio of masses, which corresponds to those histrograms. (although the axis for the ratio; bot right; is all squished.

**Comment by belledon** [comment]
i would also expect a dip in log scores around the moment of collision. is that line the log score of  the best particle?

**Comment by dominikglandorf** [comment]
Yup, I really need to redo these plots.  The "step" in the scores plot is actually "particle" and takes the final trace's log score.

**Comment by dominikglandorf** [comment]
If this is of general interest, I could collect how the traces evolve over the temporal dimension. Currently, this information is discarded during inference.

**Comment by dominikglandorf** [comment]
Screenshot 2023-09-19 at 22 01 30

**Comment by iyildirim** [comment]
so, the change-point model? adaptive computation?
________________________________

**Comment by belledon** [comment]
@iyildirim , those contributions should be made on the galileo. this is just for the basic backend of `PhyBullet`

**Comment by iyildirim** [comment]
oh sorry, good point -- and it seems we're kind of ready to move there
________________________________

**Comment by belledon** [comment]
closing since we are moving to https://github.com/CNCLgithub/PhyBullet-examples

**Pull request closed without merging**
